name: Encrypt Channels.js

on:
  push:
    paths:
      - channels.js  # Run only if channels.js changes

jobs:
  encrypt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pycryptodome

      - name: Run AES encryption
        run: |
          python encrypt_channels.py

      - name: Commit encrypted file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add channels.enc
          git commit -m "Auto-encrypted channels.js"
          git push
